services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9203:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.9.0
    container_name: kib01
    ports:
      - 5602:5602
    environment:
      ELASTICSEARCH_URL: http://es01:9202
      ELASTICSEARCH_HOSTS: http://es01:9202
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge

# version: '3'

# services:
#   es-node1:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
#     container_name: es-node1
#     environment:
#       - node.name=es-node1
#       # - discovery.seed_hosts=es-node2:9300
#       - cluster.initial_master_nodes=es-node1,es-node2
#       - cluster.name=my-cluster
#     ports:
#       - "127.0.0.1:9202:9200"
#       # - "9300:9300"
#     networks:
#       - es-net

# #   es-node2:
# #     image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
# #     container_name: es-node2
# #     environment:
# #       - node.name=es-node2
# #       - discovery.seed_hosts=es-node1:9300
# #       - cluster.initial_master_nodes=es-node1,es-node2
# #       - cluster.name=my-cluster
# #     ports:
# #       - "9203:9202"
# #       # - "9301:9300"
# #     networks:
# #       - es-net

# networks:
#   es-net:


